### ISSUE TITLE
Revert Bio4 changes and move stomp

### ISSUE THREAD

**Issue by Bleuitup** [TheRealNin/MVGA#23]
- Bring back biomass 4 as a researchable tech
- Move Stomp to biomass 9 so that it doesn't pop with two hives.

**Comment by TheRealNin** [comment]
What about nerfing stomp so that it doesn't stun for as long? Currently stomp stuns a marine for 2 seconds.

**Comment by Bleuitup** [comment]
I don't mind stomp as long as its a strictly third hive ability that helps end games provided you have onos. Lets just move it for now but ill keep that option in mind. In general my preference is to slightly move or change costs rather than changing abilities outright. Thats more overhaulish and for the time being Id like to avoid it. I want a vanilla++ feeling rather than new or different abilities except the ones that were already tried and tested in compmod for years (MT, NT)
