### ISSUE TITLE
Exo Rebalance

### ISSUE THREAD

**Issue by Bleuitup** [TheRealNin/MVGA#25]
**All Exo Types**
Decrease Tres cost to 50 (from 55)

**Minigun Exo**
* Change damage type to heavy **versus players only**
* Decrease base damage by 20% (from 10 to 8)

**Railgun Exo**
* Increase base damage by 40%
* Add a player penalty damage (like the one in the GL) equal to 28%. This way both effects cancel each other out

**Comment by TheRealNin** [comment]
fyi increased railgun full charge damage by 42.8% instead of just 40% because that makes a nice round 200 damage (previously full charge was 140)
