### ISSUE TITLE
Implement Nin's Pulse Grenade Fix

### ISSUE THREAD

**Issue by Bleuitup** [TheRealNin/MVGA#26]
This guy nin seems so cool. I heard he made a pulse nade fix :)

**Comment by TheRealNin** [comment]
One issue with this: vanilla pulse grenades deal 110 damage with a direct hit, which is almost impossible unless they are moving towards the pulse grenade or very large like a fade or onos. Empirically I deal about 65 damage to a skulk that is standing still, and about 90 damage to one running straight at me, but never the full 110. Thoughts on nerfing damage?

**Comment by Bleuitup** [comment]
Are they supposed to do how much? Do you think this is an overesight? I honestly do not know , nor the actual real role of the nade or what it should be since I never get them. I guess we can fix them and put that on hold :)
