### ISSUE TITLE
Implement GL Scaling

### ISSUE THREAD

**Issue by Bleuitup** [TheRealNin/MVGA#5]
Rationale can be found here. At it's core it aims to keep the W1 damage constant, while having a reduced W0 damage and an increased damage further into the round.
https://cdn.discordapp.com/attachments/380529761509703680/524990177505181745/GL_Model.PNG

**Changes to GL**
- Decrease base GL damage by 9%
- Let GL be affected by weapon upgrades
- Change vs player damage reduction to -33% from -20%.

(This last change will keep the W3 damage PVP the same as the current vs PVP damage of the static GL)
(Additionally, the GL will now properly scale into the round)

**Comment by TheRealNin** [comment]
Small thing: I reduced the GL damage by 8.6% instead of 9% since it makes player damage exactly 100/110/120/130 with upgrades due to the -33% reduction instead of -20% reduction.
