### ISSUE TITLE
Clog drop changes

### ISSUE THREAD

**Issue by Bleuitup** [TheRealNin/MVGA#8]
- Increase clog drop cooldown by 20%
- Increase clog drop energy cost by 20%

**Comment by TheRealNin** [comment]
Clogs share the same cooldown with all other gorge structure drops (1.0 second). Ok to increase that to 1.2 seconds?

**Comment by Bleuitup** [comment]
Sure. The idea is to make clogspam while in combat a little harder. The effect on the rest is negligible since they need to be built afterwards with right click.
